### ISSUE TITLE
Dark mode doesn't work on reference-platforms.adoc

### ISSUE THREAD

**Issue by pzmarzly** [fedora-iot/iot-docs#50] opened 2023-11-26 00:34 UTC
if you enter https://docs.fedoraproject.org/en-US/iot/reference-platforms/ with dark mode on, you will see a lot of unreadable almost-black text on black background.

Screenshot:

<img width="554" alt="SCR-20231126-blwu" src="https://github.com/fedora-iot/iot-docs/assets/8074163/43d862e8-232b-4714-acb9-83f9e09a4afb">

**Comment by nullr0ute** [comment] 2023-11-26 16:02
This is a dupe of #28

**Closed by nullr0ute** 2023-11-26 16:02 UTC
